name: Tests unit-converter-with-gui

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Tests on Python ${{ matrix.python-version }}@${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13","3.14"]
        include:
          # Add Python 3.6 and 3.7 only for Windows
          - os: windows-latest
            python-version: "3.6"
          - os: windows-latest
            python-version: "3.7"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install python-tk

      - name: Verify Tkinter availability
        run: python -c "import tkinter; print('Tkinter OK')"

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Debug workspace
        run: |
          Get-Location
          Get-ChildItem -Recurse
        shell: pwsh

      - name: Run tests
        run: python -m pytest -v tests/
